# Generated by Django 4.0.5 on 2022-07-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0003_logs_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='form',
            field=models.JSONField(blank=True),
        ),
    ]
