# Generated by Django 4.0.5 on 2022-07-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0004_alter_logs_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='form',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='method',
        ),
        migrations.AddField(
            model_name='logs',
            name='form_data',
            field=models.JSONField(default={}, verbose_name='Form data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logs',
            name='request_method',
            field=models.CharField(default='GET', max_length=50, verbose_name='Request method'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logs',
            name='path',
            field=models.CharField(max_length=300, verbose_name='Path'),
        ),
    ]
