# Generated by Django 4.0.5 on 2022-07-27 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.CharField(max_length=200)),
                ('feature_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_value', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.featurename')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.CharField(max_length=200)),
                ('group_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VendorCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code_company', models.CharField(max_length=20)),
                ('vendor_code_supplier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PropertySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.CharField(max_length=200)),
                ('property_set_name', models.CharField(max_length=200)),
                ('properties', models.ManyToManyField(to='catalog.properties')),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.propertyname'),
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.CharField(max_length=200)),
                ('inventory_name', models.CharField(max_length=200)),
                ('features', models.ManyToManyField(to='catalog.features')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.group')),
                ('property_set', models.ManyToManyField(to='catalog.propertyset')),
                ('vendor_codes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog.vendorcodes')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_length', models.IntegerField(blank=True, db_column='PathLength', null=True)),
                ('ancestor', models.ForeignKey(blank=True, db_column='ancestor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ancestor', to='catalog.group')),
                ('descendant', models.ForeignKey(blank=True, db_column='descendant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='catalog.group')),
            ],
            options={
                'db_table': 'GroupPath',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='group_path',
            field=models.ManyToManyField(through='catalog.GroupPath', to='catalog.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.group'),
        ),
    ]
